# Generated by Django 2.2.7 on 2020-03-24 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInputModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('video', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('output', models.CharField(max_length=100)),
                ('score', models.FloatField()),
            ],
        ),
    ]
