# Generated by Django 2.2.7 on 2020-03-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInputModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='quotexaminer/upload')),
                ('quote', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=100)),
                ('output', models.CharField(max_length=50)),
            ],
        ),
    ]
