# Generated by Django 2.2.7 on 2020-03-24 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotexaminer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinputmodel',
            name='added_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
