# Generated by Django 2.2.7 on 2020-03-24 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInputModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='clickbait/upload')),
                ('cluster', models.CharField(max_length=20)),
                ('output', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=1000)),
                ('pred', models.IntegerField(default=-1)),
                ('score', models.FloatField(default=-1.0)),
            ],
        ),
    ]
