# Generated by Django 2.2.7 on 2020-03-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickbait', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinputmodel',
            name='cluster',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userinputmodel',
            name='output',
            field=models.CharField(max_length=50),
        ),
    ]
